# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 14:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulos', '0001_initial'),
        ('base', '0001_initial'),
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movi',
            fields=[
                ('cmovi', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fmovi', models.DateTimeField()),
                ('descrimovi', models.CharField(max_length=80)),
                ('vttotal', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('vefe', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('vtar', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('doctar', models.CharField(max_length=10)),
                ('bantar', models.CharField(max_length=20)),
                ('vch', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('docch', models.CharField(max_length=10)),
                ('banch', models.CharField(max_length=20)),
                ('ventre', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('vcambio', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('ifcance', models.BooleanField()),
                ('fmovifin', models.DateTimeField()),
                ('ndiadeu', models.IntegerField()),
                ('ndiacobro', models.IntegerField()),
                ('vcuota', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('baseiva', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('vtiva', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('vtsuma', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('vtdescu', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('detaanula', models.CharField(max_length=80)),
                ('ccaja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Caja')),
                ('cesdo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo')),
                ('citerce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros.Tercero')),
                ('civa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Iva')),
                ('ctimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Timo')),
            ],
        ),
        migrations.CreateModel(
            name='Movideta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itmovi', models.CharField(max_length=4)),
                ('docrefe', models.CharField(max_length=10)),
                ('detalle', models.CharField(max_length=60)),
                ('vdebi', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('vcredi', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('vinte', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('prointe', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('abo_capi', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('abo_pinte', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('ndiainte', models.IntegerField()),
                ('vinte_cal', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('abo_inte', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('vcomi', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('ccta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Cta')),
                ('cmovi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.Movi')),
            ],
        ),
        migrations.CreateModel(
            name='Mven',
            fields=[
                ('cmven', models.IntegerField(primary_key=True, serialize=False)),
                ('fmven', models.DateTimeField()),
                ('docrefe', models.CharField(max_length=10)),
                ('vttotal', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('descri', models.CharField(max_length=250)),
                ('detaanula', models.CharField(max_length=250)),
                ('cbode0', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cbode0', to='base.Bode')),
                ('cbode1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cbode1', to='base.Bode')),
                ('cesdo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo')),
                ('citerce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros.Tercero')),
                ('ctimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Timo')),
            ],
        ),
        migrations.CreateModel(
            name='Mvendeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it', models.CharField(max_length=4)),
                ('nlargo', models.CharField(max_length=100)),
                ('canti', models.DecimalField(decimal_places=2, default=1, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('vunita', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('vtotal', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('carlos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Arlo')),
                ('cmven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.Mven')),
                ('ctimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Timo')),
            ],
        ),
        migrations.CreateModel(
            name='Mvsa',
            fields=[
                ('cmvsa', models.IntegerField(primary_key=True, serialize=False)),
                ('fmvsa', models.DateTimeField()),
                ('docrefe', models.CharField(max_length=10)),
                ('vttotal', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('descri', models.CharField(max_length=250)),
                ('detaanula', models.CharField(max_length=250)),
                ('cbode0', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cbode_0', to='base.Bode')),
                ('cbode1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cbode_1', to='base.Bode')),
                ('cesdo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo')),
                ('citerce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros.Tercero')),
                ('ctimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Timo')),
            ],
        ),
        migrations.CreateModel(
            name='Mvsadeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it', models.CharField(max_length=4)),
                ('nlargo', models.CharField(max_length=100)),
                ('canti', models.DecimalField(decimal_places=2, default=1, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('vunita', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('vtotal', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('carlos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Arlo')),
                ('cmvsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.Mvsa')),
                ('ctimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Timo')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='mvsadeta',
            unique_together=set([('cmvsa', 'ctimo', 'it')]),
        ),
        migrations.AlterUniqueTogether(
            name='mvsa',
            unique_together=set([('cmvsa', 'ctimo')]),
        ),
        migrations.AlterUniqueTogether(
            name='mvendeta',
            unique_together=set([('cmven', 'ctimo', 'it')]),
        ),
        migrations.AlterUniqueTogether(
            name='mven',
            unique_together=set([('cmven', 'ctimo')]),
        ),
        migrations.AlterUniqueTogether(
            name='movideta',
            unique_together=set([('cmovi', 'ccta', 'itmovi')]),
        ),
    ]
