# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terceros', '0001_initial'),
        ('articulos', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mven',
            fields=[
                ('cmven', models.AutoField(primary_key=True, serialize=False)),
                ('fmven', models.DateTimeField()),
                ('docrefe', models.CharField(max_length=10)),
                ('vttotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descri', models.CharField(max_length=250)),
                ('detaanula', models.CharField(max_length=250)),
                ('cbode0', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cbode0', to='articulos.Bode')),
                ('cbode1', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cbode1', to='articulos.Bode')),
                ('cesdo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo')),
                ('citerce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros.Tercero')),
            ],
        ),
        migrations.CreateModel(
            name='Mvendeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it', models.CharField(max_length=4)),
                ('nlargo', models.CharField(max_length=100)),
                ('canti', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vunita', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('carlos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Arlo')),
                ('cmven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.Mven')),
            ],
        ),
        migrations.CreateModel(
            name='Mvsa',
            fields=[
                ('cmvsa', models.AutoField(primary_key=True, serialize=False)),
                ('fmvsa', models.DateTimeField()),
                ('docrefe', models.CharField(max_length=10)),
                ('vttotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descri', models.CharField(max_length=250)),
                ('detaanula', models.CharField(max_length=250)),
                ('cbode0', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cbode_0', to='articulos.Bode')),
                ('cbode1', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cbode_1', to='articulos.Bode')),
                ('cesdo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo')),
                ('citerce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros.Tercero')),
            ],
        ),
        migrations.CreateModel(
            name='Mvsadeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it', models.CharField(max_length=4)),
                ('nlargo', models.CharField(max_length=100)),
                ('canti', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vunita', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('citerce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros.Tercero')),
                ('cmvsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.Mvsa')),
            ],
        ),
        migrations.CreateModel(
            name='Timo',
            fields=[
                ('ctimo', models.IntegerField(primary_key=True, serialize=False)),
                ('ntimo', models.CharField(max_length=40)),
                ('prefijo', models.CharField(max_length=4)),
                ('filas', models.IntegerField()),
                ('nrepo', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='mvsa',
            name='ctimo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.Timo'),
        ),
        migrations.AddField(
            model_name='mven',
            name='ctimo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.Timo'),
        ),
    ]
