# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terceros', '0001_initial'),
        ('movimientos', '0001_initial'),
        ('articulos', '0002_auto_20160809_1041'),
        ('base', '0003_auto_20160809_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='mvsa',
            name='citerce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros.Tercero'),
        ),
        migrations.AddField(
            model_name='mvsa',
            name='ctimo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.Timo'),
        ),
        migrations.AddField(
            model_name='mven',
            name='cbode0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbode0', to='articulos.Bode'),
        ),
        migrations.AddField(
            model_name='mven',
            name='cbode1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbode1', to='articulos.Bode'),
        ),
        migrations.AddField(
            model_name='mven',
            name='cesdo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Esdo'),
        ),
        migrations.AddField(
            model_name='mven',
            name='citerce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros.Tercero'),
        ),
        migrations.AddField(
            model_name='mven',
            name='ctimo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.Timo'),
        ),
    ]
