# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-25 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mvsa',
            name='cbode1',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cbode_1', to='articulos.Bode'),
        ),
    ]
