# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-05 07:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movi',
            name='vcred',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
