# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-24 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terceros', '0001_initial'),
        ('movimientos', '0001_initial'),
        ('articulos', '0002_auto_20170224_1035'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mvsa',
            name='citerce',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='terceros.Tercero'),
        ),
        migrations.AddField(
            model_name='mvsa',
            name='ctimo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Timo'),
        ),
        migrations.AddField(
            model_name='mvendeta',
            name='carlos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Arlo'),
        ),
        migrations.AddField(
            model_name='mvendeta',
            name='cmven',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.Mven'),
        ),
        migrations.AddField(
            model_name='mvendeta',
            name='ctimo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Timo'),
        ),
        migrations.AddField(
            model_name='mven',
            name='cbode0',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cbode0', to='base.Bode'),
        ),
        migrations.AddField(
            model_name='mven',
            name='cbode1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cbode1', to='base.Bode'),
        ),
        migrations.AddField(
            model_name='mven',
            name='cesdo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo'),
        ),
        migrations.AddField(
            model_name='mven',
            name='citerce',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='terceros.Tercero'),
        ),
        migrations.AddField(
            model_name='mven',
            name='ctimo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Timo'),
        ),
        migrations.AddField(
            model_name='movipago',
            name='banmpago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Banfopa'),
        ),
        migrations.AddField(
            model_name='movipago',
            name='cmovi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.Movi'),
        ),
        migrations.AddField(
            model_name='movipago',
            name='cmpago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.MediosPago'),
        ),
        migrations.AddField(
            model_name='movideta',
            name='cmovi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.Movi'),
        ),
        migrations.AddField(
            model_name='movi',
            name='ccaja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Caja'),
        ),
        migrations.AddField(
            model_name='movi',
            name='cesdo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo'),
        ),
        migrations.AddField(
            model_name='movi',
            name='citerce',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='terceros.Tercero'),
        ),
        migrations.AddField(
            model_name='movi',
            name='ctimo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Timo'),
        ),
        migrations.AlterUniqueTogether(
            name='mvsa',
            unique_together=set([('cmvsa', 'ctimo')]),
        ),
        migrations.AlterUniqueTogether(
            name='mvendeta',
            unique_together=set([('cmven', 'ctimo', 'it')]),
        ),
        migrations.AlterUniqueTogether(
            name='mven',
            unique_together=set([('cmven', 'ctimo')]),
        ),
    ]
