# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-26 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0002_auto_20160825_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mvsa',
            name='cbode1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cbode_1', to='articulos.Bode'),
        ),
    ]
