# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-30 10:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0003_auto_20160826_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mven',
            name='cbode0',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cbode0', to='articulos.Bode'),
        ),
        migrations.AlterField(
            model_name='mven',
            name='cesdo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo'),
        ),
        migrations.AlterField(
            model_name='mven',
            name='citerce',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='terceros.Tercero'),
        ),
        migrations.AlterField(
            model_name='mvendeta',
            name='canti',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='mvsa',
            name='cbode0',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cbode_0', to='articulos.Bode'),
        ),
        migrations.AlterField(
            model_name='mvsa',
            name='cesdo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo'),
        ),
        migrations.AlterField(
            model_name='mvsa',
            name='citerce',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='terceros.Tercero'),
        ),
        migrations.AlterField(
            model_name='mvsadeta',
            name='canti',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
