# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-31 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0004_auto_20160830_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mven',
            name='citerce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros.Tercero'),
        ),
        migrations.AlterField(
            model_name='mvsa',
            name='citerce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros.Tercero'),
        ),
    ]
