# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-23 08:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('finusu', models.DateTimeField()),
                ('fveusu', models.DateTimeField()),
                ('foto', models.ImageField(upload_to='usuarios/')),
                ('ifprises', models.BooleanField()),
                ('ccaja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Caja')),
                ('cesdo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo')),
                ('ctalomos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctalomos', to='base.Talo')),
                ('ctalopos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctalopos', to='base.Talo')),
            ],
        ),
    ]
