# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ctalomos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctalomos', to='base.Talo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ctalopos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctalopos', to='base.Talo'),
        ),
    ]
