# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-30 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='cesdo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='ape1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='ape2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='cesdo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='cpersona',
            field=models.ForeignKey(default=b'PN', on_delete=django.db.models.deletion.CASCADE, to='terceros.Personas'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='cregiva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Regiva'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='cruta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='terceros.Ruta'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='ctiide',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Tiide'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='czona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='terceros.Zona'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='nom1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='nom2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='sigla',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vende',
            name='cesdo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo'),
        ),
        migrations.AlterField(
            model_name='zona',
            name='cesdo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo'),
        ),
    ]
