# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 12:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tercero',
            old_name='cciu',
            new_name='ciudad',
        ),
        migrations.AlterField(
            model_name='vende',
            name='porventa',
            field=models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
