# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-24 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('terceros', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vende',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='cautorre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='terceros.Autorre'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='cesdo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Ciudad'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='cpersona',
            field=models.ForeignKey(default=b'PN', on_delete=django.db.models.deletion.CASCADE, to='terceros.Personas'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='cregiva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Regiva'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='cruta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='terceros.Ruta'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='ctiide',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Tiide'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='cvende',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='terceros.Vende'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='czona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='terceros.Zona'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='cesdo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo'),
        ),
        migrations.AddField(
            model_name='coti',
            name='cesdo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo'),
        ),
        migrations.AddField(
            model_name='coti',
            name='citerce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros.Tercero'),
        ),
        migrations.AddField(
            model_name='coti',
            name='ctimo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Timo'),
        ),
        migrations.AddField(
            model_name='coti',
            name='ctiservi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Tiservi'),
        ),
        migrations.AddField(
            model_name='coti',
            name='cvende',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros.Vende'),
        ),
        migrations.AddField(
            model_name='cobra',
            name='cesdo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo'),
        ),
    ]
