# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='cesdo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='cruta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='terceros.Ruta'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='czona',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='terceros.Zona'),
        ),
    ]
