# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0002_auto_20160817_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tercero',
            name='naju',
        ),
        migrations.RemoveField(
            model_name='tercero',
            name='ndiacxc',
        ),
        migrations.RemoveField(
            model_name='tercero',
            name='nomegre',
        ),
    ]
