# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-26 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0002_auto_20170508_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autorre',
            options={'ordering': ['nautorre'], 'permissions': (('list_autorre', 'Puede Listar Autorretenedores'),)},
        ),
        migrations.AlterModelOptions(
            name='tercero',
            options={'ordering': ['rasocial'], 'permissions': (('list_terceros', 'Puede Listar Terceros'),)},
        ),
    ]
