# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-08 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0002_auto_20160830_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='ordenruta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='replegal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='topcxc',
            field=models.DecimalField(blank=True, decimal_places=2, default=1000000, max_digits=15, null=True),
        ),
    ]
