#!/bin/bash
# This hook is sourced after this virtualenv is activated.

#export DATABASE_URL_DEFAULT="postgres://hgajjaumoxmjjw:20ac56e0506688add989ad3a6ea83b2dfe481cb7a4dda102b55a03cea50ada57@ec2-54-83-49-44.compute-1.amazonaws.com:5432/d3548nihdnj1r7"
#export APPEM_AWS_STORAGE_BUCKET_NAME="appemstatics"
#export APPEM_AWS_ACCESS_KEY_ID="AKIAIWI4WVWEPY3QH4DA"
#export APPEM_AWS_SECRET_ACCESS_KEY="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"
#export DATABASE_URL_PR=postgres://appem_psql_default:A7900A453403DC40F7A03E37832826F77D02E50C0BCFF1678686AA22959EA581C89C66E4F5B521231011B6FAAD651A563FCD6BE2333C25D68EC2D5E318079195@127.0.0.1:5432/appem_default
#export DATABASE_URL_FJ="postgres://zdrvqxddhzkgel:edb73a4ba9943cb1f76c10c1c4ee6d60edaca7a8139b851d75013078e97d0288@ec2-174-129-223-193.compute-1.amazonaws.com:5432/dfm9cbqe2jbkkm"
#export DATABASE_URL_PR="postgres://hgajjaumoxmjjw:20ac56e0506688add989ad3a6ea83b2dfe481cb7a4dda102b55a03cea50ada57@ec2-54-83-49-44.compute-1.amazonaws.com:5432/d3548nihdnj1r7"

export APPEM_AWS_STORAGE_BUCKET_NAME="appemstatics"
export APPEM_AWS_ACCESS_KEY_ID="AKIAIWI4WVWEPY3QH4DA"
export APPEM_AWS_SECRET_ACCESS_KEY="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"

export TEST_DATABASE_URL_DEFAULT="postgres://root:stzEF0987@127.0.0.1:5432/appem_test_default"
export TEST_DATABASE_URL_FJ="postgres://root:stzEF0987@127.0.0.1:5432/appem_test_fitnessjuice"
export TEST_DATABASE_URL_PR="postgres://root:stzEF0987@127.0.0.1:5432/appem_test_romapizza"

export APPEM_DEBUG="True"
export CURRENT_DB="test_roma_pizza_db"

export MANDRILL_API_KEY="F0iN_O0DFD9oEVd-A8zswA"
export DJANGO_SECRET_KEY="-5g%k^qyp3o@isqyrh8s80n1g-)90@msfcg)#-1xk%+*(ib)j0"
