# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0003_auto_20160809_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arlosdesglo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itglo', models.CharField(max_length=4)),
                ('cantiglo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('costoglo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vtoglo', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Arlo',
            fields=[
                ('carlos', models.IntegerField(primary_key=True, serialize=False)),
                ('cbarras', models.CharField(max_length=50)),
                ('ncorto', models.CharField(max_length=20)),
                ('nlargo', models.CharField(max_length=100)),
                ('canti', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vcosto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ifcostear', models.CharField(max_length=1)),
                ('ifpvfijo', models.CharField(max_length=1)),
                ('stomin', models.DecimalField(decimal_places=2, max_digits=15)),
                ('stomax', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pvta1', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pvta2', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pvta3', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pvta4', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pvta5', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pvta6', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vcosto1', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fcosto1', models.DateField()),
                ('vcosto2', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fcosto2', models.DateField()),
                ('vcosto3', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fcosto3', models.DateField()),
                ('ifedinom', models.CharField(max_length=1)),
                ('refe', models.CharField(max_length=20)),
                ('ifdesglo', models.CharField(max_length=1)),
                ('mesesgara', models.IntegerField()),
                ('porult1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('porult2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('porult3', models.DecimalField(decimal_places=2, max_digits=6)),
                ('porult4', models.DecimalField(decimal_places=2, max_digits=6)),
                ('porult5', models.DecimalField(decimal_places=2, max_digits=6)),
                ('porult6', models.DecimalField(decimal_places=2, max_digits=6)),
                ('foto1', models.CharField(blank=True, max_length=250, null=True)),
                ('foto2', models.CharField(blank=True, max_length=250, null=True)),
                ('foto3', models.CharField(blank=True, max_length=250, null=True)),
                ('cesdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Esdo')),
            ],
        ),
        migrations.CreateModel(
            name='Bode',
            fields=[
                ('cbode', models.AutoField(primary_key=True, serialize=False)),
                ('nbode', models.CharField(max_length=80)),
                ('esbode', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Gpo',
            fields=[
                ('cgpo', models.IntegerField(primary_key=True, serialize=False)),
                ('ngpo', models.CharField(max_length=80)),
                ('cesdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Esdo')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('cmarca', models.AutoField(primary_key=True, serialize=False)),
                ('nmarca', models.CharField(max_length=60)),
                ('cesdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Esdo')),
            ],
        ),
        migrations.AddField(
            model_name='arlo',
            name='cgpo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Gpo'),
        ),
        migrations.AddField(
            model_name='arlo',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Ciudad'),
        ),
        migrations.AddField(
            model_name='arlo',
            name='cmarca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Marca'),
        ),
        migrations.AddField(
            model_name='arlo',
            name='cubica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Ubica'),
        ),
        migrations.AddField(
            model_name='arlo',
            name='ivas_civa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Iva'),
        ),
    ]
