# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-09 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terceros', '0001_initial'),
        ('articulos', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arlo',
            name='citerce1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citerce1', to='terceros.Tercero'),
        ),
        migrations.AddField(
            model_name='arlo',
            name='citerce2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citerce2', to='terceros.Tercero'),
        ),
        migrations.AddField(
            model_name='arlo',
            name='citerce3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citerce3', to='terceros.Tercero'),
        ),
        migrations.AddField(
            model_name='arlo',
            name='cmarca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articulos.Marca'),
        ),
        migrations.AddField(
            model_name='arlo',
            name='ctiarlo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articulos.Tiarlos'),
        ),
        migrations.AddField(
            model_name='arlo',
            name='cubica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Ubica'),
        ),
        migrations.AddField(
            model_name='arlo',
            name='cunidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articulos.Unidades'),
        ),
        migrations.AddField(
            model_name='arlo',
            name='ivas_civa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Iva'),
        ),
    ]
