# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0001_initial'),
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arlo',
            name='citerce1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citerce1', to='terceros.Tercero'),
        ),
        migrations.AddField(
            model_name='arlo',
            name='citerce2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citerce2', to='terceros.Tercero'),
        ),
        migrations.AddField(
            model_name='arlo',
            name='citerce3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citerce3', to='terceros.Tercero'),
        ),
    ]
