# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-30 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arlo',
            name='cesdo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo'),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='cgpo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articulos.Gpo'),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='cmarca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articulos.Marca'),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='cubica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Ubica'),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='cunidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articulos.Unidades'),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='foto1',
            field=models.FileField(blank=True, default=b'img/articles/default.jpg', null=True, upload_to='img/articles/'),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='foto2',
            field=models.FileField(blank=True, default=b'img/articles/default.jpg', null=True, upload_to='img/articles/'),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='foto3',
            field=models.FileField(blank=True, default=b'img/articles/default.jpg', null=True, upload_to='img/articles/'),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='ivas_civa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Iva'),
        ),
        migrations.AlterField(
            model_name='arlosdesglo',
            name='cesdo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo'),
        ),
        migrations.AlterField(
            model_name='bode',
            name='cesdo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo'),
        ),
        migrations.AlterField(
            model_name='gpo',
            name='cesdo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='cesdo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo'),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='nunidad',
            field=models.CharField(default=1, max_length=60),
        ),
    ]
