# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-26 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_auto_20170508_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arlo',
            options={'ordering': ['-nlargo'], 'permissions': (('list_arlo', 'Puede Listar Articulos'), ('list_gpo', 'Puede Listar Grupos'), ('list_tiarlos', 'Puede Listar Tipo de Articulos'))},
        ),
    ]
