# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 13:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_auto_20160812_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arlo',
            name='canti',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='ifcostear',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='ncorto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='porult1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='porult2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='porult3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='porult4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='porult5',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='porult6',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='pvta1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='pvta2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='pvta3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='pvta4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='pvta5',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='pvta6',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='stomax',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='stomin',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='vcosto',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
