# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-25 14:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_auto_20170526_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='arlo',
            name='fcrea',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='arlo',
            name='npax',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gpo',
            name='impresora',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='gpo',
            name='orden',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
