# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-08 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_auto_20160831_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arlo',
            name='canti',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
