# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_auto_20160810_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arlo',
            name='ifcostear',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='ifdesglo',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='ifedinom',
            field=models.BooleanField(max_length=1),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='ifpvfijo',
            field=models.BooleanField(),
        ),
    ]
