# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0005_auto_20160810_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arlo',
            name='vcosto1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='vcosto2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='vcosto3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
