# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0006_auto_20160810_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arlo',
            name='fcosto1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='fcosto2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arlo',
            name='fcosto3',
            field=models.DateField(blank=True, null=True),
        ),
    ]
