# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esdo',
            fields=[
                ('cesdo', models.IntegerField(primary_key=True, serialize=False)),
                ('nesdo', models.CharField(max_length=40)),
                ('estavali', models.CharField(max_length=10)),
                ('colfon', models.CharField(max_length=20)),
            ],
        ),
    ]
