# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-12 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invinicab',
            name='fii',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
