# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0003_auto_20160809_1015'),
        ('inventarios', '0002_delete_esdo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invinideta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nlargo', models.CharField(max_length=100)),
                ('canti', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vunita', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cancalcu', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ajuent', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ajusal', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'invinideta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invinicab',
            fields=[
                ('cii', models.AutoField(primary_key=True, serialize=False)),
                ('fii', models.DateTimeField()),
                ('fuaii', models.DateTimeField()),
                ('cesdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Esdo')),
            ],
        ),
    ]
