# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_auto_20160812_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='invinicab',
            name='vttotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
