# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-25 11:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('cciu', models.AutoField(primary_key=True, serialize=False)),
                ('nciu', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('cdepar', models.AutoField(primary_key=True, serialize=False)),
                ('ndepar', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Esdo',
            fields=[
                ('cesdo', models.AutoField(primary_key=True, serialize=False)),
                ('nesdo', models.CharField(max_length=40)),
                ('estavali', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Iva',
            fields=[
                ('civa', models.AutoField(primary_key=True, serialize=False)),
                ('niva', models.CharField(max_length=40)),
                ('poriva', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('idtira', models.CharField(max_length=1)),
                ('cesdo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo')),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smodule', models.CharField(max_length=5)),
                ('nmodule', models.CharField(max_length=20)),
                ('enabled_enterprise', models.BooleanField()),
                ('enabled', models.BooleanField()),
                ('cesdo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo')),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cparam', models.CharField(max_length=10)),
                ('nparam', models.CharField(max_length=40)),
                ('val_boolean', models.BooleanField()),
                ('val_integer', models.IntegerField(blank=True, null=True)),
                ('val_string', models.CharField(blank=True, max_length=40, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Modules')),
            ],
        ),
        migrations.CreateModel(
            name='Regiva',
            fields=[
                ('cregiva', models.AutoField(primary_key=True, serialize=False)),
                ('nregiva', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tiide',
            fields=[
                ('idtiide', models.AutoField(primary_key=True, serialize=False)),
                ('ntiide', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Ubica',
            fields=[
                ('cubica', models.AutoField(primary_key=True, serialize=False)),
                ('nubica', models.CharField(max_length=80)),
                ('cesdo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='cdepar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Departamento'),
        ),
    ]
