# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-26 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursales',
            options={'ordering': ['csucur'], 'permissions': (('list_sucursales', 'Puede Listar Sucursales'),)},
        ),
    ]
