# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-02 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('csucur', models.AutoField(primary_key=True, serialize=False)),
                ('nsucur', models.CharField(max_length=40)),
                ('dirsucur', models.CharField(max_length=255)),
                ('telsucur', models.CharField(max_length=255)),
                ('celsucur', models.CharField(max_length=255)),
                ('cesdo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo')),
            ],
            options={
                'ordering': ['csucur'],
            },
        ),
    ]
