# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cparam', models.CharField(max_length=10)),
                ('nparam', models.CharField(max_length=40)),
                ('val_boolean', models.BooleanField()),
                ('val_integer', models.IntegerField(blank=True, null=True)),
                ('val_string', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
