# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-26 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20170526_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banfopa',
            options={'ordering': ['nbanfopa'], 'permissions': (('list_esdo', 'Puede Listar Bancos'),)},
        ),
        migrations.AlterModelOptions(
            name='bode',
            options={'ordering': ['cbode'], 'permissions': (('list_caja', 'Puede Listar Bodejas'),)},
        ),
        migrations.AlterModelOptions(
            name='caja',
            options={'ordering': ['ncaja'], 'permissions': (('list_caja', 'Puede Listar Cajas'),)},
        ),
        migrations.AlterModelOptions(
            name='ciudad',
            options={'ordering': ['cciu', 'nciu'], 'permissions': (('list_esdo', 'Puede Listar Ciudades'),)},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['ndepar'], 'permissions': (('list_esdo', 'Puede Listar Departamentos'),)},
        ),
        migrations.AlterModelOptions(
            name='esdo',
            options={'ordering': ['nesdo'], 'permissions': (('list_esdo', 'Puede Listar Estados'),)},
        ),
    ]
