# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-28 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('base', '0004_auto_20170527_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavMenus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('icon', models.TextField(max_length=255)),
                ('main', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('anchor', models.BooleanField()),
                ('url', models.TextField(blank=True, max_length=255, null=True)),
                ('general', models.BooleanField(default=False)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.NavMenus')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Modules')),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
