# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-28 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_navmenus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navmenus',
            name='permission',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
