# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-29 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20170628_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='navmenus',
            name='quick_access',
            field=models.BooleanField(default=False),
        ),
    ]
