# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-04 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_navmenus_quick_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='navmenus',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
