from django.contrib import admin

from infa_web.apps.base.models import *

admin.site.register(Esdo)
admin.site.register(MediosPago)
admin.site.register(Timo)
admin.site.register(Bode)
admin.site.register(Modules)
admin.site.register(Parameters)
admin.site.register(Ubica)
admin.site.register(Departamento)
admin.site.register(Ciudad)
admin.site.register(Iva)
admin.site.register(Regiva)
admin.site.register(Tiide)
admin.site.register(Emdor)
admin.site.register(Domici)
admin.site.register(Tifopa)
admin.site.register(Cta)
admin.site.register(Banfopa)
admin.site.register(Caja)
admin.site.register(Talo)
admin.site.register(Sucursales)
admin.site.register(NavMenus)
