import os

DEFAULT_MARCAR = 0
DEFAULT_BODEGA = 0
DEFAULT_UBICACION = 0
DEFAULT_GRUPO = 0
CESTADO_ACTIVO = 0
CESTADO_INACTIVO = 1
DEFAULT_ZONA = 0
DEFAULT_RUTA = 0

CTIARLO_ARTICULO = 1
CTIARLO_SERVICIO = 2
CTIARLO_OTRO = 3

if 'APPEMPRESARIAL_USER' in os.environ:
	APPEMPRESARIAL_USER = os.environ["APPEMPRESARIAL_USER"]
	APPEMPRESARIAL_EMAIL = os.environ["APPEMPRESARIAL_EMAIL"]
	APPEMPRESARIAL_PASS = os.environ["APPEMPRESARIAL_PASS"]

DEFAULT_IVA = 0
