# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-02 09:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Codadeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('cmesa', models.IntegerField(primary_key=True, serialize=False)),
                ('nmesa', models.CharField(max_length=50)),
                ('npmax', models.IntegerField()),
                ('cesdo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo')),
            ],
        ),
        migrations.CreateModel(
            name='Meseros',
            fields=[
                ('cmero', models.IntegerField(primary_key=True, serialize=False)),
                ('nmero', models.CharField(max_length=50)),
                ('telmero', models.CharField(max_length=50)),
                ('dirmero', models.CharField(max_length=50)),
                ('foto', models.FileField(blank=True, default=b'img/waiters/default.jpg', null=True, upload_to='img/waiters/')),
                ('cesdo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo')),
            ],
        ),
        migrations.CreateModel(
            name='Resupedi',
            fields=[
                ('cresupedi', models.IntegerField(primary_key=True, serialize=False)),
                ('fresupedi', models.DateTimeField()),
                ('vttotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('detaanula', models.CharField(max_length=250)),
                ('ifcortesia', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resupedipago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it', models.CharField(max_length=50)),
                ('docmpago', models.CharField(default=0, max_length=10)),
                ('vmpago', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('banmpago', models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='base.Banfopa')),
                ('cmpago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.MediosPago')),
                ('cresupedi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante_comandas.Resupedi')),
            ],
        ),
        migrations.CreateModel(
            name='Talocoda',
            fields=[
                ('ctalocoda', models.IntegerField(primary_key=True, serialize=False)),
                ('ntalocoda', models.CharField(max_length=50)),
                ('nini', models.IntegerField()),
                ('nfin', models.IntegerField()),
                ('cesdo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo')),
            ],
        ),
    ]
