# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-23 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('restaurante_menus', '0001_initial'),
        ('restaurante_comandas', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meseros',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario'),
        ),
        migrations.AddField(
            model_name='mesas',
            name='cesdo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo'),
        ),
        migrations.AddField(
            model_name='codadeta',
            name='ccoda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante_comandas.Coda'),
        ),
        migrations.AddField(
            model_name='codadeta',
            name='cmenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante_menus.Menus'),
        ),
        migrations.AddField(
            model_name='coda',
            name='cesdo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo'),
        ),
        migrations.AddField(
            model_name='coda',
            name='cmero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante_comandas.Meseros'),
        ),
        migrations.AddField(
            model_name='coda',
            name='cmesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante_comandas.Mesas'),
        ),
        migrations.AddField(
            model_name='coda',
            name='cresupedi',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurante_comandas.Resupedi'),
        ),
        migrations.AddField(
            model_name='coda',
            name='ctalocoda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante_comandas.Talocoda'),
        ),
    ]
