# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-20 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_comandas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coda',
            name='ccoda',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coda',
            name='ctalocoda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante_comandas.Talocoda'),
        ),
    ]
