# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-26 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_comandas', '0002_auto_20170508_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coda',
            options={'permissions': (('list_coda', 'Puede Listar Comandas'),)},
        ),
        migrations.AlterModelOptions(
            name='mesas',
            options={'ordering': ['nmesa'], 'permissions': (('list_mesas', 'Puede Listar Mesas'),)},
        ),
    ]
