# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-21 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_comandas', '0003_auto_20170526_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codadeta',
            name='cmenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Arlo'),
        ),
    ]
