# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-25 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_auto_20170526_1420'),
        ('restaurante_comandas', '0004_auto_20170721_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='codadeta',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resupedi',
            name='cfac',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.Fac'),
        ),
    ]
