# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-04 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_comandas', '0005_auto_20170725_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coda',
            options={'permissions': (('list_coda', 'Puede Listar Comandas'), ('report_resupedi', 'Puede generar reporte de Cuentas'))},
        ),
    ]
