# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 10:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
        ('base', '0001_initial'),
        ('terceros', '0001_initial'),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rue',
            fields=[
                ('crue', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('deta', models.CharField(max_length=60)),
                ('cbar_rue', models.CharField(max_length=20)),
                ('seri_rue', models.CharField(max_length=20)),
                ('cod_rue', models.CharField(max_length=20)),
                ('capaci', models.CharField(max_length=20)),
                ('veloci', models.CharField(max_length=20)),
                ('frue', models.DateTimeField()),
                ('vunita', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('pvta', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('carlos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Arlo')),
                ('cbode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Bode')),
                ('cemdor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Emdor')),
                ('cesdo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo')),
            ],
        ),
        migrations.AlterField(
            model_name='fac',
            name='cdomici',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Domici'),
        ),
        migrations.AlterField(
            model_name='fac',
            name='cemdor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Emdor'),
        ),
        migrations.AlterField(
            model_name='fac',
            name='citerce',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='terceros.Tercero'),
        ),
        migrations.AlterField(
            model_name='fac',
            name='cvende',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='terceros.Vende'),
        ),
        migrations.AddField(
            model_name='rue',
            name='cfac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.Fac'),
        ),
        migrations.AddField(
            model_name='rue',
            name='citerce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros.Tercero'),
        ),
    ]
