# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-08 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terceros', '0001_initial'),
        ('facturacion', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fac',
            name='citerce',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='terceros.Tercero'),
        ),
        migrations.AddField(
            model_name='fac',
            name='ctifopa',
            field=models.ForeignKey(default=1001, on_delete=django.db.models.deletion.CASCADE, to='base.Tifopa'),
        ),
        migrations.AddField(
            model_name='fac',
            name='cvende',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='terceros.Vende'),
        ),
    ]
