# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('facturacion', '0002_auto_20160913_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='rue',
            name='cusu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario'),
        ),
    ]
