# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-14 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('facturacion', '0002_auto_20160913_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fac',
            name='vtbruto',
        ),
        migrations.RemoveField(
            model_name='facdeta',
            name='vbruto',
        ),
        migrations.AddField(
            model_name='facdeta',
            name='civa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Iva'),
        ),
        migrations.AlterField(
            model_name='fac',
            name='ctifopa',
            field=models.ForeignKey(default=1001, on_delete=django.db.models.deletion.CASCADE, to='base.Tifopa'),
        ),
    ]
