# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-18 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_auto_20170309_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fac',
            name='ctifopa',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='base.Tifopa'),
        ),
        migrations.AlterField(
            model_name='facdeta',
            name='ncorto',
            field=models.CharField(max_length=50),
        ),
    ]
