# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-26 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_auto_20170508_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fac',
            options={'ordering': ['-femi'], 'permissions': (('add_fac_pos', 'Puede Crear Facturas POS'), ('print_fac_pos', 'Puede Imprimir facturas POS'), ('list_fac_pos', 'Puede Listar Facturas POS'), ('list_fac', 'Puede Listar Facturas'), ('print_fac', 'Puede Imprimir Facturas'), ('annulment_fac', 'Puede Anular Facturas'), ('report_fac_bill', 'Puede Generar Reporte de Ventas'), ('report_fac_bill_payment', 'Puede Generar Reporte de Ventas Por medio de Pago'))},
        ),
    ]
