# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-02 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_auto_20170418_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fac',
            options={'ordering': ['-femi']},
        ),
        migrations.AlterField(
            model_name='fac',
            name='ctifopa',
            field=models.ForeignKey(default=1001, on_delete=django.db.models.deletion.CASCADE, to='base.Tifopa'),
        ),
    ]
