# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-01 10:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('cingre', models.IntegerField(primary_key=True, serialize=False)),
                ('ningre', models.CharField(max_length=50)),
                ('canti', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('vcosto', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('ifcostear', models.BooleanField(default=True)),
                ('stomin', models.DecimalField(decimal_places=2, default=1, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('stomax', models.DecimalField(decimal_places=2, default=100, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('ifedinom', models.BooleanField(max_length=1)),
                ('foto', models.FileField(blank=True, default=b'img/ingredients/default.jpg', null=True, upload_to='img/ingredients/')),
                ('cesdo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Esdo')),
                ('civa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Iva')),
                ('cunidad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articulos.Unidades')),
            ],
            options={
                'ordering': ['-ningre'],
            },
        ),
    ]
