# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-26 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menus',
            options={'permissions': (('list_menus', 'Puede Listar Menus'),)},
        ),
        migrations.AlterModelOptions(
            name='platos',
            options={'permissions': (('list_platos', 'Puede Listar Platos'),)},
        ),
    ]
