# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-21 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_comandas', '0004_auto_20170721_0956'),
        ('restaurante_menus', '0002_auto_20170526_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gposmenus',
            name='cesdo',
        ),
        migrations.RemoveField(
            model_name='menus',
            name='cesdo',
        ),
        migrations.RemoveField(
            model_name='menus',
            name='cgpomenu',
        ),
        migrations.AlterField(
            model_name='menusdeta',
            name='cmenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Arlo'),
        ),
        migrations.DeleteModel(
            name='GposMenus',
        ),
        migrations.DeleteModel(
            name='Menus',
        ),
    ]
