# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-07 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_menus', '0003_auto_20170202_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientes',
            name='foto',
        ),
        migrations.AlterField(
            model_name='platos',
            name='fcrea',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
