# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-07 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_menus', '0004_auto_20170207_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='fcrea',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='menus',
            name='foto',
            field=models.FileField(blank=True, default=b'img/menus/default.jpg', null=True, upload_to='img/menus/'),
        ),
    ]
