# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-11 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
        ('restaurante_menus', '0005_auto_20170207_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusdeta',
            name='cunidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articulos.Unidades'),
        ),
        migrations.AddField(
            model_name='platosdeta',
            name='cunidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articulos.Unidades'),
        ),
        migrations.AlterField(
            model_name='menus',
            name='npax',
            field=models.IntegerField(default=1),
        ),
    ]
